server:
  port: 8080

spring:
  datasource:
    # H2 ???? ??????? ???? ??
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    # H2 ??????? Hibernate dialect(JPA? ??? ?????? ???? ????)
    database-platform: org.hibernate.dialect.H2Dialect
    # resources/data.yml ?? ??
    defer-datasource-initialization: true
    # ?????? ??? ??? ???? ???? ???? ????, ?????? ??? ???? ????
    hibernate:
      ddl-auto: none #create-drop
      # ??? ?? SQL? ??? ??
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      h2:
        # H2 ?? ??
        console:
          enabled: true
          path: /h2

  sql:
    init:
      mode: always

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

